lista_slap = ['https://tenor.com/view/bunny-girl-slap-angry-girlfriend-anime-gif-15144612',
            'https://tenor.com/view/anime-manga-japanese-anime-japanese-manga-toradora-gif-5373994',
            'https://tenor.com/view/anime-slap-slap-in-the-face-smash-gif-17314633',
            'https://tenor.com/view/no-angry-anime-slap-gif-7355956',
            'https://tenor.com/view/anime-slap-bitchslap-gif-18965728',
            'https://tenor.com/view/naruto-anime-slap-slapping-sakura-gif-17897226',
            'https://tenor.com/view/tower-of-god-anime-slap-gif-18815321',
            'https://tenor.com/view/anime-slap-gif-5122897',
            'https://tenor.com/view/my-collection-anime-slap-gif-16819981',
            'https://tenor.com/view/money-stare-cash-slap-fight-gif-12342551',
            'https://tenor.com/view/kename-funny-anime-slap-gif-5160096',
            'https://tenor.com/view/mio-isurugi-mm-anime-slap-gif-16250277',
            'https://tenor.com/view/oreimo-gif-10937029',
            'https://tenor.com/view/konosuba-megumin-yunyun-anime-slap-gif-17555205',
            'https://tenor.com/view/sora-kasugano-slap-anime-ouch-gif-16903818',
            'https://tenor.com/view/asobi-asobase-slap-anime-gif-17190309',
            'https://tenor.com/view/loli-cute-facepalm-slap-anime-gif-16637534',
            'https://tenor.com/view/anime-girl-slap-push-gif-12803383',
            'https://tenor.com/view/tapa-slap-anime-smile-girls-last-tour-gif-17223486',
            'https://tenor.com/view/anime-girls-student-fight-slap-gif-17423272',
            'https://tenor.com/view/sae-kashiwagi-anime-peach-girl-slap-gif-14283987']


lista_hug = ['https://tenor.com/view/anime-hug-gif-15249774',
            'https://tenor.com/view/cute-anime-hug-love-come-here-gif-7864716',
            'https://tenor.com/view/anime-choke-hug-too-tight-gif-14108949',
            'https://tenor.com/view/hug-anime-gif-4898650',
            'https://tenor.com/view/anime-cuddles-hug-in-love-gif-16329758',
            'https://tenor.com/view/anime-jump-small-gif-11098589',
            'https://tenor.com/view/noragami-yato-yukine-hug-squeeze-gif-13576354',
            'https://tenor.com/view/hug-darker-than-black-anime-gif-13976210',
            'https://tenor.com/view/anime-manga-japanese-anime-japanese-manga-kyoko-toshino-gif-5525930',
            'https://tenor.com/view/cry-sad-hug-anime-gif-5634619',
            'https://tenor.com/view/hug-anime-crying-friends-sad-gif-15974226',
            'https://tenor.com/view/anime-run-hug-gif-9096291',
            'https://tenor.com/view/cuddle-hug-anime-bunny-costumes-happy-gif-17956092',
            'https://tenor.com/view/anime-hug-anime-hug-love-gif-16121369',
            'https://tenor.com/view/hug-anime-love-you-cuddle-cuddles-gif-13601850',
            'https://tenor.com/view/come-here-ilove-you-hug-sweet-couple-gif-15769408',
            'https://tenor.com/view/anime-hug-catgirl-neko-gif-9383138',
            'https://tenor.com/view/uninhabited-planet-survive-anime-girls-anime-girls-hug-anime-hug-anime-gif-17510506',
            'https://tenor.com/view/madoka-anime-hug-pat-gif-18449042',
            'https://tenor.com/view/anime-hug-happy-glad-gif-17949869',
            'https://tenor.com/view/violet-evergarden-hug-anime-hug-hug-anime-anime-gif-17471604',]



lista_punch = ['https://tenor.com/view/anime-smash-lesbian-punch-wall-gif-4790446',
            'https://tenor.com/view/naruto-sasuke-punch-snicker-anime-gif-7380310',
            'https://tenor.com/view/anime-punch-knockout-wasted-smack-gif-11451829',
            'https://tenor.com/view/shy-punch-anime-aki-adagaki-gif-12003970',
            'https://tenor.com/view/die-anime-punch-kill-angry-gif-8932977',
            'https://tenor.com/view/punch-anime-punch-you-in-the-face-gif-5357324',
            'https://tenor.com/view/one-punch-man-saitama-anime-punch-gif-17053376',
            'https://tenor.com/view/pain-anime-punch-naruto-gif-16939589',
            'https://tenor.com/view/dyspo-dragon-ball-z-fight-power-anime-gif-17519255',
            'https://tenor.com/view/berserk-anime-punch-golden-age-arc-gif-12045798',
            'https://tenor.com/view/naruto-narutothelast-punch-anime-gif-18105611',
            'https://tenor.com/view/angry-punch-anime-gif-7885164',
            'https://tenor.com/view/mori-daiwi-god-of-highschool-fight-anime-gif-17784744',
            'https://tenor.com/view/anime-one-punch-punch-one-fight-gif-12303471',
            'https://tenor.com/view/chu-baki-kiss-hanma-punch-gif-16266430',
            'https://tenor.com/view/natsu-fairy-tail-blast-fire-punch-gif-17768945',
            'https://tenor.com/view/anime-mad-punch-beat-up-angry-gif-17346570',
            'https://tenor.com/view/anime-punch-slap-gif-15778670',
            'https://tenor.com/view/anime-punch-gif-11426252']


lista_kiss = ['https://tenor.com/view/anime-kiss-love-sweet-gif-5095865',
            'https://tenor.com/view/anime-couple-peck-cute-kiss-gif-12612515',
            'https://tenor.com/view/love-anime-kiss-hot-damn-gif-9838409',
            'https://tenor.com/view/toloveru-unexpected-surprise-kiss-gif-5372258',
            'https://tenor.com/view/poke-cheek-kiss-cute-cat-gif-15556555',
            'https://tenor.com/view/anime-ano-natsu-de-matteru-gif-9670722',
            'https://tenor.com/view/kiss-anime-cute-kawaii-gif-13843260',
            'https://tenor.com/view/kiss-anime-love-gif-4958649',
            'https://tenor.com/view/cute-kawai-kiss-anime-gif-16371489',
            'https://tenor.com/view/anime-kissing-kiss-love-gif-10356314',
            'https://tenor.com/view/golden-time-anime-kiss-gif-6155657',
            'https://tenor.com/view/kiss-anime-love-couple-gif-14240425',
            'https://tenor.com/view/anime-zero-kiss-couple-lover-gif-12925177',
            'https://tenor.com/view/kiss-love-anime-gif-12837192',
            'https://tenor.com/view/love-you-cheek-kiss-kisses-blush-gif-15049421',
            'https://tenor.com/view/kiss-anime-love-couple-intimate-gif-17193768',
            'https://tenor.com/view/anime-kiss-cute-couple-make-out-kiss-gif-13975815',
            'https://tenor.com/view/koi-to-uso-anime-kiss-gif-13344389',
            'https://tenor.com/view/yes-love-couple-kiss-in-love-gif-15009390',
            'https://tenor.com/view/anime-kiss-cute-couple-tongue-gif-14816388',
            'https://tenor.com/view/kiss-anime-love-you-couple-sweet-gif-15974229',
            'https://tenor.com/view/beso-kiss-blush-shocked-couple-gif-17916458',
            'https://tenor.com/view/kiss-anime-anime-kiss-animegirl-animeboy-gif-13387677',
            'https://tenor.com/view/anime-kissing-kiss-love-gif-10356310',
            'https://tenor.com/view/zm-kiss-make-out-couple-love-gif-15416619',
            'https://tenor.com/view/kiss-anime-shocked-blush-faint-gif-16477767',
            'https://tenor.com/view/kiss-kissing-anime-kiss-anime-love-gif-11792978',
            'https://tenor.com/view/cute-love-kiss-gif-19055016',
            'https://tenor.com/view/kiss-anime-love-gif-16047779',
            'https://tenor.com/view/cute-couple-surprised-kiss-anime-gif-14698608',
            'https://tenor.com/view/girls-anime-love-kiss-blush-gif-17708193',
]


lista_pat = ['https://tenor.com/view/headpat-pat-anime-gif-10092582',
            'https://tenor.com/view/anime-pat-smile-cute-blush-gif-16456868',
            'https://tenor.com/view/neet-anime-cute-kawaii-pat-gif-9332926',
            'https://tenor.com/view/tate-no-yuusha-no-nariagari-the-rising-of-the-shield-hero-naofumi-fitoria-shield-hero-gif-14043105',
            'https://tenor.com/view/charlotte-pat-blush-embarrassed-shy-gif-5081286',
            'https://tenor.com/view/kyo-ani-musaigen-phantomworld-izumi-anime-gif-4977531',
            'https://tenor.com/view/patpat-pat-comfort-patonthehead-therethere-gif-10534102',
            'https://tenor.com/view/anime-smile-head-pat-bed-gif-16243971',
            'https://tenor.com/view/pat-head-gif-10947495',
            'https://tenor.com/view/pet-pat-anime-kawaii-cute-gif-13236885',
            'https://tenor.com/view/head-pat-anime-kawaii-neko-nyaruko-gif-15735895',
            'https://tenor.com/view/pat-anime-gif-7453915',
            'https://tenor.com/view/anime-anime-headrub-anime-headpat-loli-kawaii-gif-16085284',
            'https://tenor.com/view/anime-pat-gif-18347273',
            'https://tenor.com/view/chobits-anime-pat-gif-10469110',
            'https://tenor.com/view/pat-head-anime-gif-7552114',
            'https://tenor.com/view/anime-pat-squidgirl-gif-9939761',
            ]

lista_casamento = ['https://tenor.com/view/anime-ring-married-marriage-marry-me-gif-12390162',
                'https://tenor.com/view/anime-wedding-marriage-wedlock-gif-10799169',
                'https://tenor.com/view/la-haut-dessin-anime-film-animation-pixard-ellie-gif-12344141',
                'https://tenor.com/view/anime-wedding-gif-10799171',
                'https://tenor.com/view/anime-wedding-marriage-wedlock-gif-10799170',
                'https://tenor.com/view/gurren-lagann-marriage-anime-ily-ilove-you-gif-16875363',
                'https://tenor.com/view/marriage-gif-19273302',
                ]